nora/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reservations.urls')),
]

reservations/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .class_views import OrderCreateView, HomeView, MenuCreateView, MenuEditView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('signup', views.signup, name='signup'),
    path(
        'login',
        auth_views.LoginView.as_view(template_name='reservations/login.html'),
        name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('menu/<uuid:unique_id>', views.menu, name='menu'),
    path('edit_menu/<uuid:unique_id>', MenuEditView.as_view(), name='edit_menu'),
    path('new_menu', MenuCreateView.as_view(), name='new_menu'),
    path('new_order/<uuid:unique_id>', OrderCreateView.as_view(), name='new_order'),
    path('menu_orders/<uuid:unique_id>', views.view_menu_orders, name='menu_orders'),
    path('view_orders/<int:user_id>', views.view_user_orders, name='user_orders')

]

reservations/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

class User(AbstractUser):
    """
    Extended User model

    Extended User model which contains whether the User is a chef or not.
    Chefs can create and edit menus, whereas regular users can only order from them.

    Attributes:

    **is_chef**
        Boolean that determines if this user is a chef (True) or a client (False)

    """
    is_chef = models.BooleanField(default=False)

class MenuManager(models.Manager):
    """
    Manager for checking the menu published today, used to avoid publishing of 2 menus in a single
    day.
    """
    def get_queryset(self):
        return super().get_queryset().filter(created__date=timezone.localdate())

class Menu(models.Model):
    """
    Model holding menu data

    A menu contains a title, the date in which it was created and last modified, as well as a
    unique id which will identify this menu.

    Attributes:

    **menu_title**
        A Char field that contains a title for this menu.

    **created**
        A Date/Time field that represents the time of creation of this menu.

    **modified**
        A Date/Time field that represents the last time this menu was modified.

    **unique_id**
        A UUID field that uniquely identifies this menu.
    """
    # Default manager
    objects = models.Manager()

    menu_title = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    todays_menu = MenuManager()

    def __str__(self):
        return self.menu_title

    def published_today(self):
        """
        returns True if this menu entry was published within today's date, False otherwise.
        """
        return timezone.localtime(self.created).date() == timezone.localdate()

    class Meta:
        ordering = ['-created']

class MenuItem(models.Model):
    """
    Model holding a specific's menu's item data

    A MenuItem is associated to a single menu, and it's just some text that represents a lunch
    option and how many times it's been ordered.

    Attributes:

    **menu**
        A Foreign key to the menu this choice is from.
    **item_text**
        A Char field with the menu's choice itself.
    **count**
        An Int field with the number of times this menu item has been ordered.
    """
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    item_text = models.CharField(max_length=200)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.item_text

class Order(models.Model):
    """
    Model holding a client's order data.

    An order contains an unique_id (since each order is indeed unique), the date it was made,
    a MenuItem selection (which in turn references the Menu), comments and a size selection from 2
    possible sizes: Normal and Large. It also contains the user that made the order.

    Attributes:

    **unique_id**
        A UUID field that uniquely identifies this order.
    **created**
        A Date/Time field that represents the time of creation of this order
    **item_choice**
        A Foreign key with this order's menu choice.
    **comments**
        A Char field with any additional comments to the order.
    **size**
        A Small Int field that represents the size choice for this order.
    **user**
        A Foreign key to the user who issued this order.
    """
    NORMAL = 0
    LARGE = 1
    MEAL_SIZES = (
        (NORMAL, 'Normal'),
        (LARGE, 'Large')
    )
    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    item_choice = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    comments = models.CharField(max_length=200, blank=True)
    size = models.SmallIntegerField(choices=MEAL_SIZES, default=NORMAL)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-created']

reservations/forms.py
from django import forms
from django.forms.models import modelformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.db.models import F
from .models import User, Menu, MenuItem, Order


class SignUpForm(UserCreationForm):
    """
    Custom SignUpForm based on a UserCreationForm, it asks (and validates) for:
    - Username
    - First Name
    - Last Name
    - Email
    - Password
    - Repeat Password
    """
    first_name = forms.CharField(max_length=30, label='Nombre')
    last_name = forms.CharField(max_length=30, label='Apellido')
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        email = {
            'required': True
        }

    def save(self, commit=True):
        """
        Override of the default save functionality for this form, ensures that a user created
        by this method is NOT a chef.
        """
        user = super().save(commit=False)
        user.is_chef = False
        if commit:
            user.save()
        return user


class MenuForm(forms.ModelForm):
    """
    Model form for filling up a menu, just shows and validates the menu title.
    """
    class Meta:
        model = Menu
        fields = ['menu_title']
        labels = {
            'menu_title': ("Título del menú")
        }


class OrderForm(forms.ModelForm):
    """
    Model form for filling up an order, the user is filled automatically.
    The items to fill are the choice from a menu, optional comments and a size.
    """
    class Meta:
        model = Order
        fields = ['item_choice', 'comments', 'size']
        labels = {
            'item_choice': ("Opción de menú"),
            'comments': ('Comentaios de la orden'),
            'size': ('Tamaño')
        }

    def save_with_user_and_add_to_count(self, user):
        """
        Method to save an Order, associate the order with a given user and add one to the count
        of the MenuItem choice.

        Arguments:

        **user**
            An User model object to associate the current entry to be saved with.
        """
        order = super().save(commit=False)
        order.user = user
        order.save()
        cur_choice = order.item_choice
        cur_choice.count = F('count') + 1
        cur_choice.save()
        return order

# ModelFormSet based on the MenuItem model, just asks for the name of the menu item,
# used for dynamic forms in the create and edit menu views.
MenuItemFormSet = modelformset_factory(
    MenuItem,
    fields=('item_text',),
    labels={'item_text': ("Nombre del plato")},
    can_delete=True,
    min_num=1,
    extra=0,
    validate_min=True)

reservations/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Menu, MenuItem, Order, User
from .utils import still_in_ordering_time
from .forms import SignUpForm
from .decorators import chef_required, login_required_message
from django.shortcuts import get_object_or_404
from django.contrib import messages


def menu(request, unique_id):
    """
    Simple view for visualizing a single menu, returns 404 if the menu does not exist,
    otherwise it gets the Menu info, it's items and if the user is a client, any order
    associated with this menu (to see if he can order or not).
    Doesn't require authentication to visualize (But cannot do much other than see the items).

    Arguments:

    **request**
        The request object which was sent to this view
    **unique_id**
        The UUID recovered from the URL that is used to retrieve the menu.
    """
    cur_menu = get_object_or_404(Menu, pk=unique_id)
    menu_items = MenuItem.objects.filter(menu__exact=cur_menu)
    context = {
        'menu': cur_menu,
        'menu_items': menu_items
    }
    if request.user.is_authenticated and not request.user.is_chef:
        try:
            if still_in_ordering_time():
                context['in_order_time'] = True
            cur_order = Order.objects.filter(user__exact=request.user, item_choice__menu=cur_menu)
            if cur_order:
                context['order'] = cur_order
        except Order.DoesNotExist:
            pass
    return render(request, 'reservations/menu.html', context)


def signup(request):
    """
    Simple view for a signup form, it uses the custom SignUpForm in order to support the additional
    user fields, this signup form is ONLY for clients, chef users need to be set via admin.
    After a succesful signup, it logins.
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            messages.success(request,"Usuario creado exitosamente!")
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'reservations/signup.html', {'form': form})


@login_required_message
@chef_required(message="Usted debe ser chef para poder ver esta página!")
def view_menu_orders(request, unique_id):
    """
    Simple view for visualizing a specific menu's associated orders, it throws 404 if the menu is
    not found. This view can only be seen by an authenticated chef user.

    Arguments:

    **request**
        The request object which was sent to this view
    **unique_id**
        The UUID recovered from the URL that is used to retrieve the menu.
    """
    cur_menu = get_object_or_404(Menu, pk=unique_id)
    menu_items = MenuItem.objects.filter(menu__exact=cur_menu)
    context = {
        'menu': cur_menu,
        'menu_items': menu_items
    }
    all_orders = Order.objects.filter(item_choice__menu=cur_menu)
    cur_page = request.GET.get('page', 1)
    paginator = Paginator(all_orders, 10)
    try:
        cur_orders = paginator.page(cur_page)
    except PageNotAnInteger:
        cur_orders = paginator.page(1)
    except EmptyPage:
        cur_orders = paginator.page(paginator.num_pages)
    context['orders'] = cur_orders
    return render(request, 'reservations/menu_orders.html', context)

@login_required_message
def view_user_orders(request, user_id):
    """
    Simple view for visualizing an user specific orders, it throws 404 if the user doesn't exist,
    or redirects with an error if the user doesn't have authorization to see the orders.

    Arguments:

    **user_id**
        A user ID derived from the URL, used to check if the user has access to this view.
    """
    cur_user = get_object_or_404(User, pk=user_id)
    if(not request.user.is_chef and cur_user != request.user):
        messages.error(request, 'Usted no esta autorizado para entrar a esta página!')
        return redirect('home')
    all_orders = Order.objects.filter(user__exact=cur_user)
    cur_page = request.GET.get('page', 1)
    paginator = Paginator(all_orders, 10)
    try:
        cur_orders = paginator.page(cur_page)
    except PageNotAnInteger:
        cur_orders = paginator.page(1)
    except EmptyPage:
        cur_orders = paginator.page(paginator.num_pages)
    return render(
        request, 'reservations/view_orders.html',
     {'orders': cur_orders, 'req_user': cur_user}
     )

reservations/templates/reservations/base.html
{% extends 'reservations/bootstrap.html' %}

{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_messages %}
{% block bootstrap3_content %}
  <nav class ="navbar navbar-default">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'home' %}">Almuerzos Nora</a>
    </div>
    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li><p class="navbar-text">Hola! {{user.get_username}}</p></li>
          {% if not user.is_chef %}
            <li>
              <a href="{% url 'user_orders' user_id=user.pk %}">
                <span class="glyphicon glyphicon-list-alt">Ordenes</span>
              </a>
              </li>
          {% endif %}        
          <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out">Salir</span></a></li>
        {% else %}
          <li><a href="{% url 'signup' %}"></a><span class="glyphicon glyphicon-user">Registrarse</span></li>
          <li><a href="{% url 'login' %}"></a><span class="glyphicon glyphicon-log-in">Iniciar</span></li>
        {% endif %}       
      </ul>
    </div>
  </nav>  
{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
{% block content %}(no content){% endblock content %}
{% endblock bootstrap3_content %}

reservations/templates/reservations/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% block bootstrap3_extra_head %}
  <script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
{% endblock %}
{% block bootstrap3_title %}
  {% block title %}
  {% endblock%}
{% endblock %}

reservations/templates/reservations/edit_menu.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}
{% load bootstrap_dynamic_formsets %}
{% block content %}
  {% for error in menu_item_form.non_form_errors %}
    {{error}}
  {% endfor %}
  <form role="form" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_dynamic_formset menu_item_form can_delete=True layout="horizontal"%}
    <button type="submit" id="form-submit" class="btn btn-success">Confirmar cambios</button>
  </form>

{% endblock content %}

reservations/templates/reservations/home.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}

{% block content %}

{% if today_menu %}
  <h2>Menú del dia</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Menú</th>
        <th>Fecha de publicación</th>
      </tr>
    </thead>
    <tbody>
      {% for menu in today_menu %}
      <tr>
        <td><a href="{% url 'menu' unique_id=menu.unique_id %}">{{menu.menu_title}}</a></td>
        <td>{{menu.created}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
<h2>Aún no se ha públicado un menú para el dia de hoy</h2>
{% endif %}
{% if menus %}
  <h2>Menus anteriores</h2>
  <table class="table">
  <thead>
    <tr>
      <th>Menú</th>
      <th>Fecha de publicación</th>
    </tr>
  </thead>
  <tbody>
    {% for menu in menus %}
      <tr>
        <td><a href="{% url 'menu' unique_id=menu.unique_id %}">{{menu.menu_title}}</a></td>
        <td>{{menu.created}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{page_obj.previous_page_number}}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}    
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% else %}
<h2>No hay ningún menu anterior aún</h2>
{% endif %}


{% if user.is_authenticated %}
  {% if  user.is_chef %}
    <h1>Bienvenido usuario chef!</h1>
    </br>
    {% if not today_menu %}
      ¡Aún no hay ningún menú para el dia de hoy {% now "j F Y" %}!
      <a href="{% url 'new_menu' %}" class="btn btn-info" role="button">Crear uno</a>
    {% endif %}
  {% else %}
    <h1>Bienvenido usuario cliente!</h1>
  {% endif %}
{% else %}
<h1>Bienvenido al sistema de almuerzos!</h1>
{% endif %}

{% endblock content %}

reservations/templates/reservations/login.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}

{% block content %}

  <form role="form" method="post">
      {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit='Login' %}{% endbuttons %}
  </form>

{% endblock content %}

reservations/templates/reservations/menu.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}

{% block content %}
<h2>{{menu.menu_title}}</h2>
  <h3>Menú del dia: {{ menu.created|date:'j F Y' }}</h3>
  <table class="table">
    <thead>
      <th>Opciones</th>
    </thead>
    <tbody>
      {% for item in menu_items %}
        <tr>
          <td>{{item.item_text}}</td>
        </tr>       
      {% endfor %}
    </tbody>
  </table>
{% if user.is_authenticated %}
  {% if user.is_chef %}
    <a class="btn btn-primary" href="{% url 'menu_orders' unique_id=menu.unique_id %}" role="button">
      Ver ordenes
    </a>
    <a class="btn btn-success" href="{% url 'edit_menu' unique_id=menu.unique_id %}" role="button">
        <span class="glyphicon glyphicon-edit">Editar</span>
    </a>
  {% else %}
    {% if not menu.published_today or not in_order_time%}
      ¡Ya pasó el tiempo para pedir de este menú!
    {% elif order %}
      ¡Usted ya ordenó de este menú!
    {% else %}
      <a class="btn btn-primary" href="{% url 'new_order' unique_id=menu.unique_id %}" role="button">
        <span class="glyphicon glyphicon-shopping-cart">Ordenar</span>
      </a>
    {% endif %}
  {% endif %}
{% else %}     
  ¡Identificate para poder ordenar!
{% endif %}
{% endblock content %}

reservations/templates/reservations/menu_orders.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}

{% block content %}
{% if user.is_authenticated and user.is_chef %}
  <h2>Opciones de menú</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Opción</th>
        <th>Número de pedidos</th>
      </tr>
    </thead>
    <tbody>
      {% for item in menu_items %}
        <tr>
          <td>{{item.item_text}}</td>
          <td>{{item.count}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Ordenes</h2>
  {% if orders.object_list.all %}
    <table class="table">
      <thead>
        <tr>
          <th>Usuario</th>
          <th>Opción de menú</th>
          <th>Tamaño de menú</th>
          <th>Comentarios</th>
        </tr>     
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>
            <td>{{order.user.get_username}}</td>
            <td>{{order.item_choice}}</td>
            <td>{{order.get_size_display}}</td>
            <td>{{order.comments}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if orders.has_other_pages %}
      <ul class="pagination">
        {% if orders.has_previous %}
          <li><a href="?page={{ orders.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in orders.paginator.page_range %}
          {% if orders.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if orders.has_next %}
          <li><a href="?page={{ orders.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
  {% else %}
    <h3>Nadie ha ordenado de este menú</h3>
  {% endif %}
{% else %}
<h2>¡Usted no tiene autorización para ver esta página!</h2>
{% endif %}

{% endblock content %}

reservations/templates/reservations/new_menu.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}
{% load bootstrap_dynamic_formsets %}
{% block content %}
  {% for error in menu_item_form.non_form_errors %}
    {{error}}
  {% endfor %}
  <form role="form" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_dynamic_formset menu_item_form can_delete=True layout="horizontal"%}
    <div class="checkbox">
      <label><input type="checkbox" name="notify_mail">¿Desea notificar este menú por correo?</label>
    </div>
    <div class="checkbox">
      <label><input type="checkbox" name="notify_slack">¿Desea notificar este menú por el canal de Slack?</label>
    </div>
    <button type="submit" id="form-submit" class="btn btn-success">Crear</button>
  </form>

{% endblock content %}

reservations/templates/reservations/new_order.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}
{% block content %}

  <form role="form" method="post">
    {% csrf_token %}
    <h2>Orden para menú: {{menu.menu_title}}</h2>
    {% bootstrap_form form %}
    {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
  </form>

{% endblock content %}

reservations/templates/reservations/signup.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}

{% block content %}

  <form role="form" method="post">
      {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
  </form>

{% endblock content %}

reservations/templates/reservations/view_orders.html
{% extends 'reservations/base.html' %}
{% load bootstrap3 %}

{% block content %}
{% if user.is_authenticated %}
  <h2>Ordenes anteriores de: {{req_user.get_username}}</h2>
  {% if orders.object_list.all %}
    <table class="table">
      <thead>
        <tr>
          <th>Menú</th>
          <th>Opción de menú</th>
          <th>Tamaño de menú</th>
          <th>Comentarios</th>
          <th>Fecha</th>
        </tr>     
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>
            <td>{{order.item_choice.menu}}</td>
            <td>{{order.item_choice}}</td>
            <td>{{order.get_size_display}}</td>
            <td>{{order.comments}}</td>
            <td>{{order.created}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if orders.has_other_pages %}
      <ul class="pagination">
        {% if orders.has_previous %}
          <li><a href="?page={{ orders.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in orders.paginator.page_range %}
          {% if orders.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if orders.has_next %}
          <li><a href="?page={{ orders.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
  {% else %}
    <h3>Sin ordenes aún</h3>
  {% endif %}
{% else %}
<h2>¡Usted no tiene autorización para ver esta página!</h2>
{% endif %}

{% endblock content %}